import type { DefaultTheme } from 'vitepress'
import { existsSync, readFileSync } from 'node:fs'
import { defineConfig } from 'vitepress'

// docs/api is generated by `bun run generate` and not committed, so read it at runtime
const sidebarFile = new URL('../api/typedoc-sidebar.json', import.meta.url)
const typedocSidebar: DefaultTheme.SidebarItem[] = existsSync(sidebarFile)
	? JSON.parse(readFileSync(sidebarFile, 'utf8'))
	: []

// https://vitepress.dev/reference/site-config
export default defineConfig({
	title: 'Home',
	titleTemplate: 'Alwe\'s Tools - :title',
	description: 'A collection of data structures, algorithms, and utilities for TypeScript',
	head: [['link', { rel: 'icon', href: '/tools/favicon.svg' }]],
	lastUpdated: true,
	cleanUrls: true,
	base: '/tools/',
	vite: {
		build: {
			// the local search index holds the whole API reference and is only loaded when search opens
			chunkSizeWarningLimit: 1000,
		},
	},
	themeConfig: {
		search: {
			provider: 'local',
		},
		nav: [
			{ text: 'Home', link: '/' },
			{ text: 'Docs', link: '/introduction' },
			{ text: 'API', link: '/api/' },
		],
		sidebar: [
			{
				text: 'Documentation',
				items: [
					{
						text: 'Introduction',
						link: '/introduction',
					},
					{
						text: 'Getting Started',
						link: '/getting-started',
					},
				],
			},
			{
				text: 'API Reference',
				items: [
					{
						text: 'Overview',
						link: '/api/',
					},
					...typedocSidebar,
				],
			},
		],
		socialLinks: [
			{ icon: 'github', link: 'https://github.com/zAlweNy26/tools' },
			{ icon: 'npm', link: 'https://www.npmjs.com/package/@danyalwe/tools' },
		],
	},
})
